version: "3.8"

services:
  postgres:
    image: "postgres:16-alpine"
    container_name: sql_injection_lab
    environment:
      POSTGRES_DB: isob_lab_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_data:
    driver: local

networks:
  postgres_network:
    driver: bridge
